config/routes.rb
TestRorProject::Application.routes.draw do
  resources :authentications

  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'utils#home'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :update]

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'utils/home', to: 'utils#home'
  match '/about',   to: 'utils#about'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %b RoR test app
    by Skvirskiy Roman
  %nav
    %ul
      %li= link_to "About",  about_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "test RoR app", root_path, id:"logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method:"delete"
          - else
            %li
              = link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = include_gon
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/shim'
    %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCN-KY4D8roJ6OH67bTYzCeYExC2rATNXE&sensor=false", :type => "text/javascript"}
  %body
    = render 'layouts/header'
    .container
      %div{:class => "msg"}
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?